# Generated by Django 4.1.7 on 2023-03-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="gender",
            field=models.TextField(default="Male", max_length=12),
            preserve_default=False,
        ),
    ]
