# Generated by Django 4.1.7 on 2023-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signin", "0002_register_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pictures")),
            ],
        ),
    ]
