# Generated by Django 4.1.7 on 2023-03-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signin", "0003_uploadimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadimage",
            name="image",
            field=models.ImageField(upload_to="picture"),
        ),
    ]
